// ============================================================
// AI OS — Full Agent Catalog (50 Specialized Agents)
// ============================================================

import { Agent } from './types';

export const agents: Agent[] = [
  // ── Core AI ─────────────────────────────────────────────────
  {
    id: 'chat',
    name: 'Chat',
    description: 'General-purpose conversational AI for open-ended dialogue',
    category: 'core',
    icon: 'MessageCircle',
    status: 'online',
    capabilities: ['conversation', 'Q&A', 'brainstorming', 'reasoning'],
  },
  {
    id: 'memory',
    name: 'Memory',
    description: 'Manages long-term context and recalls past interactions',
    category: 'core',
    icon: 'Brain',
    status: 'online',
    capabilities: ['context recall', 'preference tracking', 'session memory'],
  },
  {
    id: 'search',
    name: 'Search',
    description: 'Real-time web search with source attribution',
    category: 'core',
    icon: 'Search',
    status: 'online',
    capabilities: ['web search', 'fact checking', 'source citing'],
  },
  {
    id: 'browser',
    name: 'Browser',
    description: 'Navigates and extracts information from web pages',
    category: 'core',
    icon: 'Globe',
    status: 'online',
    capabilities: ['web scraping', 'page analysis', 'link extraction'],
  },
  {
    id: 'collaboration',
    name: 'Multi-Agent',
    description: 'Orchestrates multi-agent workflows and task decomposition',
    category: 'core',
    icon: 'Network',
    status: 'online',
    capabilities: ['task routing', 'agent coordination', 'result merging'],
  },

  // ── Content Creation ────────────────────────────────────────
  {
    id: 'document',
    name: 'Document',
    description: 'Creates and edits documents, reports, and articles',
    category: 'content',
    icon: 'FileText',
    status: 'online',
    capabilities: ['writing', 'editing', 'formatting', 'templates'],
  },
  {
    id: 'pdf',
    name: 'PDF',
    description: 'Parses, extracts, and generates PDF documents',
    category: 'content',
    icon: 'FileDown',
    status: 'online',
    capabilities: ['PDF parsing', 'text extraction', 'PDF generation'],
  },
  {
    id: 'presentation',
    name: 'Presentation',
    description: 'Designs professional slide decks and pitch presentations',
    category: 'content',
    icon: 'Presentation',
    status: 'online',
    capabilities: ['slide design', 'layout', 'export'],
  },
  {
    id: 'spreadsheet',
    name: 'Spreadsheet',
    description: 'Builds formulas, pivot tables, and data spreadsheets',
    category: 'content',
    icon: 'Table',
    status: 'online',
    capabilities: ['formulas', 'charts', 'pivot tables', 'CSV/Excel'],
  },
  {
    id: 'writing',
    name: 'Writing',
    description: 'Creative and technical writing assistant with style control',
    category: 'content',
    icon: 'PenTool',
    status: 'online',
    capabilities: ['copywriting', 'blogging', 'storytelling', 'tone adjustment'],
  },
  {
    id: 'research',
    name: 'Research',
    description: 'Deep research with synthesis across multiple sources',
    category: 'content',
    icon: 'BookOpen',
    status: 'online',
    capabilities: ['literature review', 'synthesis', 'citations'],
  },
  {
    id: 'translation',
    name: 'Translation',
    description: 'Multi-language translation with cultural context',
    category: 'content',
    icon: 'Languages',
    status: 'online',
    capabilities: ['translation', 'localization', '100+ languages'],
  },
  {
    id: 'summarization',
    name: 'Summarization',
    description: 'Condenses long content into key takeaways',
    category: 'content',
    icon: 'ListCollapse',
    status: 'online',
    capabilities: ['summarization', 'key points', 'TL;DR'],
  },

  // ── Creative AI ─────────────────────────────────────────────
  {
    id: 'image-gen',
    name: 'Image Generator',
    description: 'Generates images from text prompts using AI models',
    category: 'creative',
    icon: 'Image',
    status: 'online',
    capabilities: ['text-to-image', 'style transfer', 'variations'],
  },
  {
    id: 'image-edit',
    name: 'Image Editor',
    description: 'Edits, enhances, and transforms existing images',
    category: 'creative',
    icon: 'ImagePlus',
    status: 'online',
    capabilities: ['editing', 'retouching', 'background removal', 'upscaling'],
  },
  {
    id: 'video-gen',
    name: 'Video Generator',
    description: 'Creates short videos from prompts or scripts',
    category: 'creative',
    icon: 'Video',
    status: 'online',
    capabilities: ['text-to-video', 'animation', 'motion graphics'],
  },
  {
    id: 'video-edit',
    name: 'Video Editor',
    description: 'Edits, trims, and enhances video content',
    category: 'creative',
    icon: 'Film',
    status: 'online',
    capabilities: ['trimming', 'transitions', 'subtitles', 'effects'],
  },
  {
    id: 'audio',
    name: 'Audio & Music',
    description: 'Generates music, sound effects, and audio content',
    category: 'creative',
    icon: 'Music',
    status: 'online',
    capabilities: ['music generation', 'SFX', 'mixing', 'mastering'],
  },
  {
    id: 'voice',
    name: 'Voice',
    description: 'Text-to-speech and voice cloning capabilities',
    category: 'creative',
    icon: 'Mic',
    status: 'online',
    capabilities: ['TTS', 'voice cloning', 'narration', 'podcast'],
  },
  {
    id: 'avatar',
    name: 'Avatar',
    description: 'Generates digital avatars and character portraits',
    category: 'creative',
    icon: 'UserCircle',
    status: 'online',
    capabilities: ['avatar creation', 'style variations', 'animation'],
  },
  {
    id: 'meme',
    name: 'Meme',
    description: 'Creates trending memes with custom text and images',
    category: 'creative',
    icon: 'Smile',
    status: 'online',
    capabilities: ['meme templates', 'text overlay', 'trending formats'],
  },
  {
    id: 'thumbnail',
    name: 'Thumbnail',
    description: 'Designs eye-catching thumbnails for videos and content',
    category: 'creative',
    icon: 'LayoutGrid',
    status: 'online',
    capabilities: ['thumbnail design', 'A/B variants', 'platform-specific'],
  },
  {
    id: 'branding',
    name: 'Logo & Branding',
    description: 'Creates logos, brand kits, and visual identity systems',
    category: 'creative',
    icon: 'Palette',
    status: 'online',
    capabilities: ['logo design', 'color palette', 'brand guidelines'],
  },

  // ── Developer ───────────────────────────────────────────────
  {
    id: 'code-gen',
    name: 'Code Generator',
    description: 'Writes code in 50+ languages from natural language specs',
    category: 'developer',
    icon: 'Code',
    status: 'online',
    capabilities: ['code generation', 'boilerplate', 'algorithms'],
  },
  {
    id: 'debugging',
    name: 'Debugger',
    description: 'Identifies and fixes bugs with root cause analysis',
    category: 'developer',
    icon: 'Bug',
    status: 'online',
    capabilities: ['bug detection', 'root cause analysis', 'fix suggestions'],
  },
  {
    id: 'refactoring',
    name: 'Refactoring',
    description: 'Optimizes and refactors code for performance and readability',
    category: 'developer',
    icon: 'RefreshCcw',
    status: 'online',
    capabilities: ['code optimization', 'patterns', 'clean code'],
  },
  {
    id: 'testing',
    name: 'Testing',
    description: 'Generates unit, integration, and e2e test suites',
    category: 'developer',
    icon: 'TestTube',
    status: 'online',
    capabilities: ['unit tests', 'integration tests', 'coverage analysis'],
  },
  {
    id: 'docs',
    name: 'Documentation',
    description: 'Generates API docs, READMEs, and technical documentation',
    category: 'developer',
    icon: 'BookMarked',
    status: 'online',
    capabilities: ['API docs', 'README', 'inline comments', 'JSDoc'],
  },
  {
    id: 'security',
    name: 'Security',
    description: 'Audits code for vulnerabilities and security best practices',
    category: 'developer',
    icon: 'Shield',
    status: 'online',
    capabilities: ['vulnerability scan', 'OWASP', 'dependency audit'],
  },
  {
    id: 'devops',
    name: 'DevOps',
    description: 'CI/CD pipelines, Docker, Kubernetes, and infrastructure',
    category: 'developer',
    icon: 'Container',
    status: 'online',
    capabilities: ['CI/CD', 'Docker', 'K8s', 'IaC'],
  },
  {
    id: 'database',
    name: 'Database',
    description: 'Schema design, query optimization, and migrations',
    category: 'developer',
    icon: 'Database',
    status: 'online',
    capabilities: ['SQL', 'NoSQL', 'schema design', 'query optimization'],
  },
  {
    id: 'ai-ml',
    name: 'AI/ML',
    description: 'Machine learning model training, fine-tuning, and deployment',
    category: 'developer',
    icon: 'Cpu',
    status: 'online',
    capabilities: ['model training', 'fine-tuning', 'evaluation', 'deployment'],
  },

  // ── Business ────────────────────────────────────────────────
  {
    id: 'marketing',
    name: 'Marketing',
    description: 'Campaign strategies, ad copy, and growth tactics',
    category: 'business',
    icon: 'Megaphone',
    status: 'online',
    capabilities: ['campaigns', 'ad copy', 'social media', 'growth hacking'],
  },
  {
    id: 'analytics',
    name: 'Analytics',
    description: 'Business analytics, KPI tracking, and performance dashboards',
    category: 'business',
    icon: 'BarChart3',
    status: 'online',
    capabilities: ['KPI tracking', 'dashboards', 'reporting', 'insights'],
  },
  {
    id: 'finance',
    name: 'Finance',
    description: 'Financial modeling, budgeting, and forecasting',
    category: 'business',
    icon: 'DollarSign',
    status: 'online',
    capabilities: ['financial models', 'budgets', 'forecasts', 'analysis'],
  },
  {
    id: 'legal',
    name: 'Legal',
    description: 'Contract analysis, compliance checks, and legal drafting',
    category: 'business',
    icon: 'Scale',
    status: 'online',
    capabilities: ['contracts', 'compliance', 'legal drafting', 'review'],
  },
  {
    id: 'seo',
    name: 'SEO',
    description: 'Search engine optimization and keyword strategy',
    category: 'business',
    icon: 'TrendingUp',
    status: 'online',
    capabilities: ['keyword research', 'on-page SEO', 'content strategy'],
  },

  // ── Productivity ────────────────────────────────────────────
  {
    id: 'email',
    name: 'Email',
    description: 'Drafts, manages, and summarizes email communications',
    category: 'productivity',
    icon: 'Mail',
    status: 'online',
    capabilities: ['email drafting', 'replies', 'summarization', 'templates'],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    description: 'Schedules meetings, manages events, and finds optimal times',
    category: 'productivity',
    icon: 'Calendar',
    status: 'online',
    capabilities: ['scheduling', 'conflicts', 'reminders', 'time zones'],
  },
  {
    id: 'task-manager',
    name: 'Task Manager',
    description: 'Organizes tasks, tracks progress, and manages deadlines',
    category: 'productivity',
    icon: 'CheckSquare',
    status: 'online',
    capabilities: ['task tracking', 'priorities', 'deadlines', 'kanban'],
  },
  {
    id: 'notes',
    name: 'Notes',
    description: 'Smart note-taking with auto-organization and linking',
    category: 'productivity',
    icon: 'StickyNote',
    status: 'online',
    capabilities: ['note-taking', 'organization', 'linking', 'search'],
  },

  // ── Data & Intelligence ─────────────────────────────────────
  {
    id: 'data-analysis',
    name: 'Data Analysis',
    description: 'Analyzes datasets with statistical methods and insights',
    category: 'data',
    icon: 'LineChart',
    status: 'online',
    capabilities: ['statistics', 'trends', 'correlations', 'insights'],
  },
  {
    id: 'visualization',
    name: 'Visualization',
    description: 'Creates charts, graphs, and interactive data visualizations',
    category: 'data',
    icon: 'PieChart',
    status: 'online',
    capabilities: ['charts', 'graphs', 'dashboards', 'interactive viz'],
  },
  {
    id: 'report-gen',
    name: 'Report Generator',
    description: 'Generates comprehensive reports from data and analysis',
    category: 'data',
    icon: 'ClipboardList',
    status: 'online',
    capabilities: ['report writing', 'data synthesis', 'executive summaries'],
  },
  {
    id: 'ocr',
    name: 'OCR & Vision',
    description: 'Extracts text from images, scans, and handwriting',
    category: 'data',
    icon: 'ScanText',
    status: 'online',
    capabilities: ['OCR', 'handwriting', 'table extraction', 'image analysis'],
  },

  // ── Education ───────────────────────────────────────────────
  {
    id: 'tutor',
    name: 'Tutor',
    description: 'Personalized tutoring across subjects with adaptive learning',
    category: 'education',
    icon: 'GraduationCap',
    status: 'online',
    capabilities: ['tutoring', 'explanations', 'practice problems', 'adaptive'],
  },
  {
    id: 'quiz',
    name: 'Quiz Generator',
    description: 'Creates quizzes, exams, and assessment materials',
    category: 'education',
    icon: 'HelpCircle',
    status: 'online',
    capabilities: ['quiz creation', 'multiple choice', 'grading', 'feedback'],
  },
  {
    id: 'interview-coach',
    name: 'Interview Coach',
    description: 'Mock interviews with feedback for job preparation',
    category: 'education',
    icon: 'UserCheck',
    status: 'online',
    capabilities: ['mock interviews', 'feedback', 'behavioral', 'technical'],
  },

  // ── Entertainment ───────────────────────────────────────────
  {
    id: 'story-writer',
    name: 'Story Writer',
    description: 'Writes short stories, novels, and narrative content',
    category: 'entertainment',
    icon: 'BookHeart',
    status: 'online',
    capabilities: ['storytelling', 'world building', 'character development'],
  },
  {
    id: 'script-writer',
    name: 'Script Writer',
    description: 'Writes screenplays, video scripts, and dialogue',
    category: 'entertainment',
    icon: 'Clapperboard',
    status: 'online',
    capabilities: ['screenplays', 'video scripts', 'dialogue', 'storyboards'],
  },

  // ── Automation ──────────────────────────────────────────────
  {
    id: 'workflow',
    name: 'Workflow Automation',
    description: 'Automates multi-step workflows with triggers and actions',
    category: 'automation',
    icon: 'Workflow',
    status: 'online',
    capabilities: ['automation', 'triggers', 'scheduling', 'webhooks'],
  },
  {
    id: 'api-integration',
    name: 'API Integration',
    description: 'Connects and manages third-party API integrations',
    category: 'automation',
    icon: 'Plug',
    status: 'online',
    capabilities: ['REST APIs', 'OAuth', 'webhooks', 'data sync'],
  },
];

export const getAgentsByCategory = (category: string) =>
  agents.filter((a) => a.category === category);

export const getAgentById = (id: string) =>
  agents.find((a) => a.id === id);

export const getOnlineAgents = () =>
  agents.filter((a) => a.status === 'online');
